FromDoppler/relay-webapp

src/wwwroot/styles/modules/_daterange.scss, src/wwwroot/styles/modules/_dropdown.scss
See:
* https://github.com/MakingSense/Doppler_Relay/pull/797
* https://github.com/MakingSense/Doppler_Relay/commit/aed391bed222f8ea4ebae6e2f64139fb176f38de
* https://github.com/MakingSense/Doppler_Relay/commit/57dc8751d8d94747471c0752ebe18aed54d5688c
=> DR-914 - Apply changes from `release/v1.0.0-beta20` branch

src/wwwroot/styles/modules/_dropdown.scss
=> DR-919 Fix issue with dropdown arrow

src/wwwroot/styles/modules/_dropdown.scss
Change:
- Increase min-width so we don't get a cropped date.
=> DR-929 Fix cropped DateRange

src/protractor-conf-builder.js
Change:
- Modify the protractor's browser size.
=> DR-949 Fix protractor window size

src/wwwroot/partials/header.html, src/wwwroot/partials/reports/reports.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/modules/_modal.scss, src/wwwroot/styles/views/_header.scss, src/wwwroot/styles/views/_reports.scss
Changes:
- Fix issue with logout menu.
- Fix issue with search input in Reports.
- Resize header.
- Fix issue in downloads.
=> DR-957 Fix several responsive issues

src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/modules/_chart.scss, src/wwwroot/styles/views/_reports.scss, src/wwwroot/styles/views/_settings.scss, src/wwwroot/styles/views/_templates.scss
Changes:
- Use class instead of directive in css selector.
- Fix C3 font-size.
- Fix too small date.
- Fix API y settings connections view.
- Full width button in templates
=> DR-957 Fix issues with big data user and small fixes

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/services/settings.js, src/wwwroot/styles/views/_settings.scss
Changes:
- Add test for Add Domain.
- Uncomment Add Domain functionality.
- Css for Responsive Add Domain Layout
=> DR-963 Correct markup, uncomment add domain functionality and fix responsive issues

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/services/settings.js
Changes:
- Add call to service.
- Add content.
- Add html for make default domain.
WIP: 
- Confirmation text or icon for setting the default Domain.
=> DR-965 Set Domain Default

src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/partials/settings/domain-manager.html
Change:
- Send logic from controller to the view.
=> DR-965 Fix issue

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/services/settings.js
Changes:
- Add Activate functionality.
- Refactor Add domain call to use the same as Activate.
- Add Activate Test.
=> DR-967 - Activate domain

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/services/settings.js
Changes:
- Add Test.
- Add controller.
- Add service.
- Change html.
=> DR-966 Add view, controller, service and test for deleting a domain

src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js
Changes:
- Rename default domain response in controller.
- Rename default domain in test mocking.
=> DR-958 Rename defaultDomain to default in api response parsing

src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/services/utils.js
Changes:
- Add a new service inside utils for reseting an input.
- Refactor registration Ctrl and add it to domain Ctrl.
=> DR-975 Clear input after submit

src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_settings.scss
Changes:
- Change ng-repeat.
- Add function to apply property to each new element, set default or disabled.
- Remove old animation.
=> DR-958 Fix issue with duplicated elements in table

src/wwwroot/controllers/DomainManagerCtrl.js
Hi @mvillaseco,
I have done a little changes:
* Reduce the highlight time
* Add highlight after activate
* Add highlight to previous default domain
* Minor code style fixes
=> Minor improvements

src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/modals/ErrorCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/modals/error.html, src/wwwroot/services/settings.js
Changes:
- Add error handling in Domain controller.
- Change error handling in Main controller.
- Modify error modal html.
- Modify error modal Ctrl.
WIP: 
- Content
=> DR-976 Deal with exceptions functionality

src/spec/page-objects/dkim-page.js, src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/app.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/controllers/dKimConfigCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/styles/views/_settings.scss
Changes:
- Add final Content.
- Add new controller.
- Add new view.
- Add link in domains table
- Add test to be improved.
=> DR-Add Dkim information to app

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/styles/views/_settings.scss
Changes:
- Add View and css to add SPF into dkim config.
WIP: 
- Lack of final Content.
=> DR-922 Change view

src/wwwroot/index.html
Change:
- Add Google Analytics script.
=> DR-1002 Add google analytics in WebApp

src/spec/settings_spec.js, src/wwwroot/controllers/dKimConfigCtrl.js, src/wwwroot/partials/settings/dkim-configuration-help.html
Changes:
- Change Dkim format and Selector.
- Fix broken test.
=> DR-1005 Change dkim format and fix test

src/wwwroot/controllers/dKimConfigCtrl.js, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/styles/views/_settings.scss
=> DR-1005 Fix issue with public key

src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/services/signup.js, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_login.scss
Changes:
- Remove Domain from Registration.
- Add Company to registration.
- Fix tests.
- Add responsive behaviour.
=> DR-857 - New fields pages

src/bower.json, src/gulpfile.js, src/karma.conf.js, src/wwwroot/app.js, src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/index.html, src/wwwroot/lists/countries.js, src/wwwroot/lists/industries.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/styles/modules/_dropdown.scss, src/wwwroot/styles/shame.scss
Changes:
- Add dropdown angular-ui-select into app.
- Fill dropdown.
- Add dropdown into view.
WIP: 
- Real Countries and real Industries.
=> Dr 857 Add dropdown to app

src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html
Hi team,
I added the validation in UI of phone number
=> DR-1025 - Add Phone Number validation in Activation form

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js
FYI, I am waiting JP feedback about the message.
=> DR-1027 - Change error message for invalid account name

src/bower.json, src/gulpfile.js, src/karma.conf.js, src/wwwroot/app.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/index.html, src/wwwroot/partials/signup/registration.html
Hi team, it completes AccounName field based on Company name as you can see in attached video. Could you review?
https://www.dropbox.com/s/54jkdcwexavesqi/Video_2017-04-28_160632.wmv?dl=0
=> DR-1019 - Fill accountname

src/gulpfile.js, src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/services/signup.js, src/wwwroot/styles/modules/_dropdown.scss, src/wwwroot/styles/views/_login.scss
Change:
- Remove value from checkbox.
- Add login into controller
- Removed logic from service.
=> DR-857 Fix terms and conditions issue

src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/modules/_dropdown.scss
=> DR-1030 - Fix focus in selectors in Activation Form

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js
Change:
- Add "spf" text before "fromdoppler.com" text
=> DR-1050 Added spf text into locals

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/styles/modules/_table.scss, src/wwwroot/styles/views/_settings.scss
Changes:
- Add Drop down into view.
- Add function to predefine each domain choice options.
- Style dropdown to match the prototype.
- Fix tests.
- Fix responsive issue.
=> Dr-1033 add dropdown into domain status

src/wwwroot/styles/views/_settings.scss
Change:
- Change how the library was setting the right arrow in the dropdowns inside settings.
=> DR-1035 Fix issue with arrow

src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/styles/views/_settings.scss
Changes: 
- Fix double default status.
- Change dropdown style.
- Change dropdown positioning.
- Change table padding.
=> DR-1035 Fix issue with double default in domain lists and style issues

src/wwwroot/styles/views/_settings.scss
Change:
- Add ng-hide default functionality.
=> dr-1070 Fix issue with flashy dropdown in domain settings status

src/spec/page-objects/dkim-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/dKimConfigCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/partials/settings/domain-manager.html
Hi team,
I added icons of dKim and Spf status as in domains list page
Example:
=> DR-1035 - Configuration Page - Add icons status dkim and spf

src/spec/page-objects/settings-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/controllers/dKimConfigCtrl.js, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/partials/settings/domain-manager.html, src/wwwroot/services/settings.js
Hi team,
I added the endpoint in dkim configuration help page to use values SPF and DKIM status, DKIM selector and Dkim public key
=> DR-1090 - Add get Domain data to dkim configuration help page

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js
I added translation of marketing team in configuration page 
=> DR-1104 - Configuration Page - Add subtitle translation in dkim configuration

src/wwwroot/partials/settings/dkim-configuration-help.html
Hi,
I change the style of subtitle text in SPF and Dkim Configuration.
Example:
=> DR-1074 - Dkim Configuration Page - Change style of subtitle

src/wwwroot/controllers/DomainManagerCtrl.js, src/wwwroot/controllers/MyProfileCtrl.js, src/wwwroot/controllers/SettingsCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/header.html, src/wwwroot/styles/views/_header.scss
TLDR: This PR changes the submenues making it like this:
- My Profile, My Plan and Billing
- SMTP & API and Domain Manager
and the only way to access between them it's from the upper right menu.
Changes:
- Modified sub menues
- Add menu into upper right menu.
WIP: I'm waiting for final Content.
=> DR-1112 Fix submenues to be used in the future

src/bower.json, src/gulpfile.js, src/karma.conf.js, src/wwwroot/app.js, src/wwwroot/index.html, src/wwwroot/styles/_modules.scss, src/wwwroot/styles/modules/_slider.scss
TLDR: Adds slider.
Changes:
- Add new slider.
=> DR-1110 Add Slider 

src/bower.json, src/gulpfile.js, src/karma.conf.js, src/wwwroot/app.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/modules/_button.scss, src/wwwroot/styles/views/_settings.scss
Add new billing page.
- Add billing page layout
- Add billing credit card validation mask.
- Add billing credit card exp date mask.
- Add required validations(not for credit card) and expdate validations.
- Link My plan with billing page
- Responsive ready.
- Test
=> Dr-1122 Add billing page

src/gulpfile.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/partials/settings/my-plan.html
Fix some issues found
- Add slider css into build.
- Add sort in case of API doesn't sort them.
- Add behaviour when default plan it's not in the current plans array(selects the first).
- Add forgotten brakets.
=> DR-1111 Fix issues with slider

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/styles/views/_settings.scss
Shows the selected price with his price and also add a behaviour of select the first plan when the plan selected it's not available.
-  Modify Billing controller. 
-  Modify html and css.
-  Add a load function.
=> DR-1159 Add plan details into billing page with not founded plan behaviour

src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/partials/settings/billing.html
Add mask into security code setted by credit card type.
- Add new mask
- Add new property to all masks that doesn't erase the input value on blur.
=> DR-1160 Add mask to security code

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/utils.js, src/wwwroot/styles/modules/_button.scss, src/wwwroot/styles/views/_settings.scss
Add confirmation Page to app.
- Add new page html, controller and layout.
- Add transition for changing page with confirmation.
-  Remove type of consumer input
- Tests.
- Hide Credit Card first numbers and sec code.
=> Dr-1163 add billing confirmation

src/karma.conf.js, src/spec/billing_spec.js, src/spec/confirmation_spec.js, src/spec/page-objects/billing-page.js, src/spec/page-objects/confirmation-page.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/index.html, src/wwwroot/partials/settings/billing.html, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/services/resources.js, src/wwwroot/services/settings.js, src/wwwroot/services/signup.js, src/wwwroot/styles/views/_settings.scss
Hi team,
I added country combo in the Billing page with the same countries of activation flow
Example:
=> Dr 1153 - Billing page - Add Country combo

src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/settings.js
Add payment workflow.
- Add function to call service.
- Add service to post required data and redirect to reports after.
=> DR-1162 Add button for start billing process

src/wwwroot/partials/settings/billing.html
Hi team,
I add autocomplete off in credit card number, expiration date and security code
=> dr-1174 - Billing page - add autocomplete="off"

src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/settings.js
Fix several issues
- Fix text in buy button
- Fix API url type
- Fix Values sent to API.
=> DR-1175 Fix button text, API url typo and api values sent

src/wwwroot/partials/settings/billing.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_header.scss, src/wwwroot/styles/views/_settings.scss
Fix alignment vertically, small refactor adding transition and bug with small phones
- Modify vertically alignment to flex start with a margin.
- Change error containers locally adding a transition and positioning differently from others(maybe in a near future we should do this for everyone).
- Fix for small phones like Iphone 5 are now accepted.
=> DR-1179 Fix alignment vertically issue

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/utils.js, src/wwwroot/services/utilsService.spec.js
Add credit card validation and also Luhn algorithm.
- Add new method in utils service.
- Add Validation error for this case.
- Add tests.
=> DR-1167 Add credit card validation with Luhn validation also

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/settings.js, src/wwwroot/styles/modules/_button.scss
Add error handling for 400 errors.
- Add new module "detached--error" for cases when we have to show an error not related to an input.
- Detached--error works with max-height making posible to show future errors with a nice transition.
- Add error handling
- Test
=> DR-1167 Add 400 error handling behaviour

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/services/settings.js, src/wwwroot/styles/modules/_button.scss, src/wwwroot/styles/modules/_slider.scss, src/wwwroot/styles/views/_settings.scss
Add plan information layout and some tests.
- Add plan information layout.
- Set service and controller.
- Add Tests.
=> Dr-1194 show plan values

src/wwwroot/partials/settings/billing.html, src/wwwroot/styles/views/_settings.scss
Change alginment for server error label.
- Change display aligment of the label error section.
- Fix for mobile also.
=> [DR-1200] Fix issue in firefox with server error label

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/services/reports.js, src/wwwroot/services/settings.js
Add current plan status from user.
- Add tests
- Add new behaviour
- Modify getReports service call to allow use "per_page" filter
- Hide upgrade functionality when user is not free trial
- Set hidden menu ready to be ready when we finished this functionality
=> Dr-1203 show current plan status

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/MyProfileCtrl.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/header.html, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/styles/views/_header.scss, src/wwwroot/styles/views/_settings.scss
Add link so the users can get into My Plan section now.
- Add link into submenu and settings menu.
- Hide upgrade button for non free trial users.
- Replace price and cost per emails for Free trial users.
- Change transition for spinner, it was too slow.
=> [DR-1208] Add link to my plan section and free trial behaviour

src/karma.conf.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/controllers/modals/GeneralTemplateCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/modals/general-template.html
Add popup after successful payment.
- Add new modal
- Add general template for the future
- Fix issue.
=> Dr-1216 show popup indicating upgrade successful

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html
New translation for "USD" so that each language can use the right version for USD.
=> [DR-1245] Remove USD in English

src/karma.conf.js, src/wwwroot/directives/validation-errors-fluid.js, src/wwwroot/index.html, src/wwwroot/styles/_core.scss, src/wwwroot/styles/core/_validations.scss, src/wwwroot/styles/shame.scss
This PR adds new validations directive.
- New directive
- New scss file for directives
- Fix issue with error border on inputs
- Add transition when the error is shown.
=> [DR-1251] Add new validations directive with fluid design

src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/modules/_dropdown.scss
Change stlye from all select box in the app to match the same style than the regular inputs.
- Change in base.scss 
- Change in dropdown.scss
=> [DR-1261] Change style for active status in every select box

src/wwwroot/styles/views/_templates.scss
Fix bug replacing old Jeet alignment.
- Change templates stylesheet
=> [DR-1262] Remove old jeet alignment and fix the bug

src/spec/billing_spec.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/partials/settings/my-plan.html
Add translations to currency.
- Modify billing view.
=> [DR-1258] Fix bug with translations in billing currency

src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/core/_settings.scss, src/wwwroot/styles/modules/_button.scss, src/wwwroot/styles/views/_templates.scss
This PR will change the background "grey" colour in all the app. And also change the background color and border from the inputs.
- Change background color "grey" in app.
- Change focus and not focus input styles.
=> [DR-1268] Change background app color and inputs colors

src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html
Add text to show if the account it's closed or not.
- Add scope variable
- Add text.
- Text in spanish
=> [DR-1280] Add text to show if the account its closed or not

src/wwwroot/styles/views/_settings.scss
Hi team
I fix the postal code field
Issue:
Fix
=> [DR-1261] - Fix postal code in spanish

build-webapp.cmd
This script will be used in Andres' environment to automatize package generation for Production environment.
Example: `build-webapp PROD`
=> [DR-1302] Add a simple script to update and build WebApp

src/spec/billing_spec.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/partials/settings/my-plan.html
Add cost by ip to final pricing and add ip count into my plan information.
- Modify plan price when user is Pro.
- Add Ip count to plan info.
=> [DR-1299] Add new line to my plan info and add real price for pro plans

src/spec/billing_spec.js, src/wwwroot/partials/settings/my-plan.html
Reduce cost per email decimals to 5 and fix some tests.
- Reduce cost per email decimals.
- Fix Tests
=> [DR-1312] reduce decimals cost per email

src/wwwroot/controllers/BillingCtrl.js
Fix issue with value in billing page.
- Add ip count and cost by ip values into the final price.
=> [DR-1313] Fix issue with price not adding ips values

src/spec/page-objects/reports-page.js, src/spec/reports_spec.js, src/wwwroot/controllers/ReportsCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/reports/reports.html, src/wwwroot/services/reports.js, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_reports.scss
Add limits by day into Reports page for users that have this limit.
- Add limit into view, controller and service.
- Manage locals.
- Add test.
- Responsive Handle
=> [DR-1341] Add daily rate limit

src/wwwroot/partials/settings/my-plan.html
Changed link for my plan premium button link.
=> [DR-1365] Replace link from premium button sending an email to linked the website

src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/ReportsCtrl.js, src/wwwroot/controllers/modals/GeneralTemplateCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/modals/general-template.html, src/wwwroot/services/auth.js
Add new popup to show the user that the free trial has expired.
- Add new modal
- Add content
- Tests
=> Dr-1283 Add popup trial ended

src/wwwroot/index.html
Change the flag due to refactor in mainCtrl
- Change name of the flag used.
=> [DR-1283] Change the flag to show or not full screen with new bar or not

src/wwwroot/index.html
Fix issue with footer(scroll was being shown when it shouldn't).
=> [DR-1283] Fix class validations to add class for correct footer alignment

src/wwwroot/controllers/MainCtrl.js, src/wwwroot/services/auth.js
Hi,
The header is not displayed because of doesn't have `data ` object
=> [DR-1370] - Fix Free header upgrade is not displayed

src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/ReportsCtrl.js, src/wwwroot/partials/reports/reports.html, src/wwwroot/services/auth.js, src/wwwroot/services/reports.js
Hi @alegarciamina, there were some issues related to limits loading, I tried to fix one by commit, could you review?
I hope to deploy it to PROD environment tomorrow.
=> [DR-1395] Issues on recurrent loading of limits

README.md, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/ReportsCtrl.js, src/wwwroot/partials/reports/reports.html, src/wwwroot/services/auth.js, src/wwwroot/services/reports.js
It fixes some issues with limits pulling.
=> Releases/v1.0.0 Beta35 Hotfix 1

src/wwwroot/controllers/MainCtrl.js
Hi team, it is a very little change.
=> Refresh limits status each 30 seconds

src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/MyProfileCtrl.js, src/wwwroot/controllers/modals/ErrorCtrl.js, src/wwwroot/interceptors/errorHandlerInterceptor.js, src/wwwroot/partials/modals/error.html, src/wwwroot/services/reports.js, src/wwwroot/services/signup.js
Hi team, 
This PR fixes many issues on dealing with error responses, two of them related to authorization errors that where not redirecting to login.
It also includes a change in error dialog behavior: now we are executing the callback (refresh or redirect to login) only if the user clicks in the dialog button.
=> [DR-1374] Error dealing with AJAX errors

src/wwwroot/partials/modals/copy-to-clipboard.html, src/wwwroot/partials/modals/error.html, src/wwwroot/partials/modals/general-template.html, src/wwwroot/partials/modals/welcome.html
Fix missaligned close button from modals
- Added proper class to align the button
=> [DR-1389] Fix close button from modals

src/spec/settings_spec.js, src/wwwroot/directives/copy-to-clipboard.js
Hi team,
I've implemented a fix for Copy Api key functionality.
=> [DR-1257] Fix copy Api key

src/spec/billing_spec.js, src/wwwroot/services/settings.js
Hi team,
I've replaced `POST agreements` with `PUT agreements/current` for upgrades.
=> [DR-1413] Use PUT agreements/current for upgrades

src/wwwroot/partials/settings/my-plan.html
Scroll to plans position in order to give a better UX for the user.
- Add "duScroll" directive.
=> [DR-1420] Scroll to plans position inside My Plan page

src/wwwroot/index.html
Set the position of the pages always on top.
- Add directive autoscroll.
=> [DR-1419] Add scroll to top as a Default

src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/partials/settings/billing.html
Disable submit button while processing the upgrade request.
=> [DR-1421] Prevent multiple clicks on upgrade button

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/header.html, src/wwwroot/styles/views/_header.scss
Add link into header
- Add link and css.
- Add content.
=> [DR-1418] Add update link in desktop version

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/services/settings.js, src/wwwroot/styles/views/_settings.scss
Show to the user a scheduled warning message
- Add message
- Mobile ready
=> [DR-1412] Add scheduled message in my plan

src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_login.scss
Separate Country code and area code from phone number and store in the datebase with "-".
- Add 2 new inputs
- Fix style issues
- Fix Responsive
=> Dr-1428 separate phone number

src/gulpfile.js
Hi team,
I've added a gulp task to copy hcheck.png to deploy folder.
Could you please review?
=> [DR-1426] Copy hcheck.png to deploy folder

src/wwwroot/partials/signup/registration.html
Hi team,
this is to enforce users to accept terms and conditions on signup.
=> [DR-1433] Signup: terms and conditions required

src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/app.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/controllers/SucceedRegistrationCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/header.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/partials/signup/succeed.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_login.scss
Open new registration to the world 
- Add new succeed page.
- Fix css issues.
- Succeed Responsive.
=> [DR-1440] Add new registration Flow

src/bower.json, src/gulpfile.js, src/karma.conf.js, src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/app.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/index.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/services/signup.js, src/wwwroot/styles/views/_login.scss
Add recaptcha.
- Install new directive
- Modify header
=> [DR-1446] Add Recaptcha

src/wwwroot/controllers/RegistrationCtrl.js
Fix issue with instance of captcha
=> [DR-1446] Fix issue with captcha

src/wwwroot/partials/signup/registration.html, src/wwwroot/styles/views/_login.scss
Refactor Registration
- Correct Alignment 
- Remove old validation when it's possible
=> Dr-1454 Refactor registration

src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_login.scss
Small refactor of confirmation page to align correctly inputs, buttons and mobile fixes.
- Remove mediaquery for height.
- Remove old validation when it's possible.
- Correct alignments.
=> Dr-1459 refactor confirmation page

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/signup/confirmationPage.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/styles/views/_login.scss
#Overview
Small refactor with UX changes.
=> [DR-1454] Small refactor

src/spec/page-objects/profile-page.js, src/wwwroot/app.js, src/wwwroot/controllers/ChangeEmailCtrl.js, src/wwwroot/controllers/MyProfileCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-profile.html, src/wwwroot/services/auth.js, src/wwwroot/services/settings.js, src/wwwroot/styles/views/_settings.scss
**Changes**
- Change password refactor
- Add change email form
- Add `/change-email` page to confirm new email address
=> [DR-827] Change email

src/spec/forgot-password_spec.js, src/spec/login_spec.js, src/spec/page-objects/billing-page.js, src/spec/page-objects/dkim-page.js, src/spec/page-objects/login-page.js, src/wwwroot/controllers/LoginCtrl.js, src/wwwroot/partials/login/login.html, src/wwwroot/partials/settings/dkim-configuration-help.html, src/wwwroot/partials/settings/my-plan.html
Fix warnings and Forgot password page.
=> [Dr-1469] Fix webapp tests

src/spec/billing_spec.js, src/spec/page-objects/billing-page.js, src/spec/page-objects/login-page.js, src/spec/page-objects/profile-page.js, src/spec/page-objects/settings-page.js, src/spec/settings_spec.js
=> [DR-1469] Fix tests, reorder actions and rename function

src/spec/page-objects/profile-page.js, src/spec/settings_spec.js, src/wwwroot/controllers/HeaderCtrl.js, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/header.html, src/wwwroot/partials/settings/my-profile.html, src/wwwroot/styles/views/_header.scss, src/wwwroot/styles/views/_settings.scss
Add language flags in header for Desktop version only and inside of my profile page for desktop and mobile version.
- Add global function
- Add flags
- Css changes
=> [DR-1491] Add Change languaje inside profile page and in header nav bar

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/login/login.html, src/wwwroot/partials/signup/registration.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_header.scss, src/wwwroot/styles/views/_login.scss
Add a link to come and go back from login to registration. Also fix several css bugs.
- Css fixes(iphone 5 ready)
- Add link.
@andresmoschini @alegarciamina
=> Dr-1492 link from login to registration and backwards

src/spec/login_spec.js, src/spec/page-objects/login-page.js, src/wwwroot/app.js, src/wwwroot/controllers/LoginAdminCtrl.js, src/wwwroot/index.html, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/login/login-admin.html, src/wwwroot/services/auth.js
Add Login Admin Page 
- Add new page
- Add new content
- Final endpoint
- Tests
=> Dr-1498 Add login admin page

src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/ReportsCtrl.js
Load limits when the user logs in or get into reports page.
- Add global function
=> [DR-1472] Add new global function to load limits when user logs in

src/wwwroot/partials/login/login-admin.html
=> [DR-1488] Remove hardcoded text

src/wwwroot/index.html
Replace old GA script to GTM
This PR will not be merged until we test correctly the script
=> [DR-1435] Replace old GA with GTM

src/wwwroot/acceptanceTests/login.spec.js, src/wwwroot/acceptanceTests/routing.spec.js, src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/ReportsCtrl.js, src/wwwroot/services/auth.js
It tries to fix the issue with showing obsolete limits data, could you review?
I did not test it yet, but I will directly test it in QA environment.
=> [DR-1515] Call loadLimits after load and after login

src/wwwroot/directives/breadcrumb.js, src/wwwroot/index.html, src/wwwroot/partials/directives/breadcrumb.html, src/wwwroot/styles/core/_base.scss
Add a breadcrumb first version
=> [DR-1518] First breadcrumb version

src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/app.js, src/wwwroot/confirmationPage.html, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/index.html
Change to send the user to confirmation from website so the guys can track new registrations while we test some changes in GA.
=> Dr-1503 add new page for ga

src/wwwroot/controllers/MainCtrl.js, src/wwwroot/controllers/SettingsCtrl.js, src/wwwroot/partials/header.html, src/wwwroot/styles/views/_header.scss
Fix issues with menu and Submenu
- Change submenu position.
- Add underline for menues.
- Add style
=> [DR-1525] Fix issues with menues and submenues

src/wwwroot/directives/breadcrumb.js, src/wwwroot/partials/header.html, src/wwwroot/partials/settings/domain-manager/dkim-configuration-help.html, src/wwwroot/styles/core/_base.scss, src/wwwroot/styles/views/_header.scss
Add hover active state and transition
- Refactor submenu active state.
- Add hover to main menues.
=> [DR-1525] Add hover and transitions to active state

src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js
=> DKIM status can take up to 24 hours to update

src/wwwroot/app.js, src/wwwroot/directives/link-toggler.js, src/wwwroot/index.html, src/wwwroot/partials/header.html, src/wwwroot/services/auth.js, src/wwwroot/styles/views/_header.scss
Task: We need to add multi account users into the application that can only view certain pages.
PR: Remove links that are not allowed to users with profile permissions and redirect them in case of a not allowed page access.
- Add directive to handle links.
- Add redirect in case of access into not allowed page.
- Tests
=> [DR-1545] Add directive to remove not available links and redirect routing to allowed pages

src/wwwroot/partials/header.html, src/wwwroot/styles/views/_header.scss
Fix issue with header links not being displayed and small css fix.
=> [DR-1546] Refresh header links before login

src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/controllers/RegistrationCtrl.js, src/wwwroot/partials/login/login.html, src/wwwroot/services/signup.js
Add origin into registration data from user in order to use it in zoho lead. Also add origin description when the user comes from login.
=> [Dr-1517] Add origin to registration user data

src/wwwroot/partials/settings/my-plan.html
QA testing result in change a validation in plan view
Add validation on pro premium button to disable state
N/A
This is a fix of the pr #223
N/A
=> [DR-1561] Add one more require domain validation to show button

src/spec/page-objects/new-plan.js, src/spec/settings_spec.js, src/wwwroot/controllers/PlanCtrl.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/services/auth.js, src/wwwroot/styles/views/_settings.scss
Update logic and plan view to validate using deliveries constraint
* Add new property from api
* Add localization messages
* Update styles
* Add tests
N/A
I update the styles due to pseudo element last-of-type was being applied only in the last <li> element, that was ok for 1 message but now we have a max of two messages 2, with the new styles the box support unlimited number of messages and without bugs.
=> [DR-1578] Create deliveries validation in frontend

src/spec/page-objects/new-plan.js, src/wwwroot/locales/en-translation.js, src/wwwroot/locales/es-translation.js, src/wwwroot/partials/settings/my-plan.html, src/wwwroot/styles/views/_settings.scss
Add a message to show the ready step 1 and pending step 2
Update styles
Add texts to language file
Update plans view
Update test
Add style to the list number
N/A
@mvillaseco What do you think about the changes?
=> [DR-1596] Add ready step 1 message

src/wwwroot/services/utils.js
We need setup the real domain for the new brand
Update domain in utils script and reCaptcha account
~~Request TLS protocol~~
~~Set new domain in reCaptcha~~
~~We are waiting confirmation about if the new domain will implement TLS and waiting for the reCaptcha account credentials from @dnoya~~
=> [DR-1516] Set gire domain

src/wwwroot/template-editor/index.html, src/wwwroot/template-editor/rev-manifest.json
=> [DR-1622] Add editor and override Adapter

src/wwwroot/template-editor/adapterService.js
Move Relay demo files to own folder in cdn to test our mocked adapterService
Create folder in cdn to relay demo files "relay-demo-content"
N/A
N/A
=> [DR-1622] Move fake images to relay folder in cdn

src/wwwroot/template-editor/index.html
Add loader references to index page to prevent delay when angular app.js is loading from cdn
* Add loader icon attached to index page
* Add loader code
N/A
N/A
=> [DR-1622] Add loader to mseditor relay index page

src/wwwroot/template-editor/adapterService.js
Integrate webapp language with mseditor
Add initializer in adapterService
Method to get language from localstorage 
N/A
Locale files are stored locally.
=> [DR-1639] Get language from webapp local storage

src/wwwroot/services/auth.js
Fix issue in gulp build process in uglify library
Add error paremeter in catch clausule
N/A
N/A
=> Fix uglify issue in build process

src/gulpfile.js, src/wwwroot/template-editor/index.html
We need to bundle the local js files used in the template editor
Created new tasks to create js bundle
Inject bundle name in index.html
N/A
The bundle is generated by environment files from wwwroot/env
=> [DR-1644] Create bundle js to template editor

src/wwwroot/template-editor/adapterService.js
Create a js bundle with version  number to mseditor's local dependencies
Update getCampaign method to send request
Handle errors
Log errors in console
N/A
RELAY_CONFIG service was replaced for a mocked one until the environment config integration is ready
Error:
=> [DR-1644] Call to backend and handle error for getCampaign

src/wwwroot/template-editor/index.html
(I will update the version number after merging https://github.com/MakingSense/MSEditor/pull/1268)
=> [DR-1653] Update MSEditor version to load languages from CDN

src/wwwroot/template-editor/index.html
Using https://github.com/MakingSense/MSEditor/pull/1270
=> [DR-1657] Update reference to MSEditor to get ngLocale files from CDN

src/wwwroot/controllers/ConfirmationCtrl.js, src/wwwroot/partials/signup/confirmationPage.html
Remove checkbox from confirmation page.
- Remove view references
- Remove controller references
=> [DR-1660] Remove checkbox from confirmation page

src/spec/confirmation_spec.js, src/wwwroot/acceptanceTests/signup.spec.js, src/wwwroot/controllers/MainCtrl.js
=> [DR-1660] Change terms version

src/wwwroot/partials/signup/registration.html, src/wwwroot/services/signup.js
Uncomment send promotions check and send the data to the backend.
=> [DR-1668] Uncomment and send promotions check data

src/wwwroot/template-editor/adapterService.js
Get and Save MsEditor content
- Modify adapter.
=> Dr 1675 get and save mseditor

src/spec/page-objects/template-page.js, src/spec/template_spec.js, src/wwwroot/controllers/TemplateCtrl.js, src/wwwroot/services/templates.js
Update webapi template calls to use new methods to get template's body
Add new methods on template api service
Call to template body service methods on template controller
Add tests to edit and create templates
~Tests~
~Error handling~
We will do the error handling when EditTemplateBody fails later.
=> [DR-1680] Update webapp template calls

src/wwwroot/template-editor/adapterService.js
Fix issue with return response from adapter
=> [DR-1675] Change get campaign response in adapter

src/wwwroot/styles/views/_templates.scss
Add cursor pointer in mseditor option for templates.
=> [DR-1704] Add cursor pointer in new mseditor button template option

src/wwwroot/template-editor/adapterService.js
In progress advance for the adapter, still need some tests.
=> [DR-1686] Get image gallery mocked.

src/wwwroot/template-editor/adapterService.js
Fix issue and add a small refactor.
=> [DR-1686] Refactor to fix an issue with sorting

src/build-w-docker.sh, src/package.json, src/yarn.lock
Hi Team, these changes allow us to run Protractor tests in our _Pristine Jenkins_ using Docker.
=> Run tests with Docker

src/wwwroot/polyfills/string.prototype.includes.js, src/wwwroot/template-editor/adapterService.js
Use href from the links instead of the obsolete thumbnail property.
=> [DR-1750] Use links for the thumbnails

src/wwwroot/template-editor/adapterService.js, src/wwwroot/template-editor/index.html
Something weird happen with #315, so I am opening this new PR from @VicThorX branch.
> Hi !
> 
> With help of @andresmoschini I made changes on adapterService to accept array of objects instead array of strings, and send Delete request with the file id to API.
> 
> Could anybody review it? and help me if I wrong.
> 
> It replaces #314 
What is happening:
=> [DR-1766] Allow to delete files

src/build-w-docker.sh, src/wwwroot/hcheck.html
Simple PR to add a new file to the load balancer can verify if the server is active
=> [DR-1843] Add hcheck.html

src/gulpfile.js, src/package.json, src/protractor-conf-builder.js, src/spec/billing_spec.js, src/spec/confirmation_spec.js, src/spec/login_spec.js
Added missing files after build the webapp.
=> [NO-TICKET] Add files on build task

src/wwwroot/env/INT.js, src/wwwroot/env/PROD.js, src/wwwroot/env/QA.js
Hi team!
This change is related to [PR-143](https://github.com/MakingSense/doppler-swarm/pull/143)
=> Update CUIT Service URL

src/wwwroot/controllers/TemplatesCtrl.js, src/wwwroot/partials/templates/templates.html, src/wwwroot/services/auth.js, src/wwwroot/services/templates.js, src/wwwroot/styles/views/_templates.scss
Hi team!
This PR is related to [Relay 2088 PR](https://github.com/MakingSense/Doppler_Relay/pull/2088)
=> [DM-504] Add new profile Read Only Tempaltes

src/spec/billing_spec.js, src/wwwroot/controllers/BillingCtrl.js, src/wwwroot/partials/settings/billing.html, src/wwwroot/services/resources.js
Support is added to be able to select provinces or states for other countries in addition to Argentina, especially for the United States.
To do this, the structure of the countries.json resource file was modified in Doppler_Relay so that it has the Country-> Province hierarchy and stopping using the provinces.json file and is removed.
=> feat: add support for manage provinces to differents countries

src/wwwroot/template-editor/index.html
This PR wants to change to version v1.0.1-build170 of the MSEditor.
=> Html broken template editor
