FromDoppler/relay-webapp

- src/wwwroot/partials/signup/registration.html
When moving across the registration form fields using the TAB key, the form ends in an invalid state. This happens because we have a hidden password field which is required.
Avoid rendering password field
> DR-1073 Avoid rendering password field in the registration form

- src/wwwroot/controllers/ConfirmationCtrl.js
- src/wwwroot/directives/debounced-ng-click.js
- src/wwwroot/index.html
- src/wwwroot/partials/signup/confirmationPage.html
On activation page, if the user clicks on the confirmation button several times, it generates several API calls
- Add new `debounced-ng-click` directive in charge of preventing new submits if a promise is in progress
- Adjust `submitActivation` function so it returns a promise
If this approach is approved we should consider using this directive in every element that causes an API call. In those cases, we should adjust controller code so the involved functions returns a promise
> DR-1069 Prevent form to be submitted more than once

- src/wwwroot/locales/es-translation.js
Hi team,
I fix the amount deliveries per month is not displayed in the Spanish language
> DR-897 - Fix Spanish amount deliveries is not displayed

- src/karma.conf.js
- src/wwwroot/services/settings.js
- src/wwwroot/services/settings.spec.js
It is to avoid to request our API when the plan list is already loaded in client memory.
In the future we should avoid this kind of patches and make a goo use of HTTP cache, but I think that by the moment it is useful.
> DR-1156 - Plans cache

- src/spec/page-objects/billing-page.js
- src/wwwroot/styles/views/_settings.scss
Hi team
I resolved the icons should be displayed in Firefox browser, also when the system detects the credit card, the icon should change the colour
Pending: Update the tests
Examples:
> Dr 1178 - Fix credit card icons not visible in Firefox

- src/protractor-conf-builder.js
- src/spec/billing_spec.js
- src/wwwroot/controllers/PlanCtrl.js
- src/wwwroot/partials/settings/my-plan.html
- src/wwwroot/services/settings.js
Hi Team,
The My Consumption and Plan Renewal fields in My plan section through a new endpoint GET `account/status/plan`
Example:
Now, the hour is displayed in PLAN RENEWAL
> [DR-1225] - Add /status/plan endpoint in the App

- src/wwwroot/env/INT.js
- src/wwwroot/env/PROD.js
- src/wwwroot/env/QA.js
This PR is intended to change the URL set up in the configuration files to make the calls through HTTPS in order to avoid the browser security errors
> [Hot Fix] [DR-1158] Make API calls through HTTPS only

- src/protractor-conf-builder.js
- src/spec/billing_spec.js
- src/spec/page-objects/billing-page.js
- src/spec/settings_spec.js
- src/wwwroot/app.js
- src/wwwroot/locales/en-translation.js
- src/wwwroot/locales/es-translation.js
- src/wwwroot/partials/settings/my-plan.html
Hi team,
I added the format separator number in all WebApp by language
This repository has a code to the use of this PR - angular-dynamic-locale code
https://github.com/lgalfaso/angular-dynamic-locale/blob/master/src/tmhDynamicLocale.js#L18
Example
https://user-images.githubusercontent.com/6796523/28466274-4c8b8206-6e02-11e7-9960-fbe93ae15d6c.png
Configuration i18n
Spanish
https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.6.5/angular-locale_es-419.js
English
https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.6.5/angular-locale_en-150.js
> [DR-1253] - Add separator numbers by language

- src/wwwroot/partials/settings/domain-manager.html
- src/wwwroot/styles/modules/_dropdown.scss
- src/wwwroot/styles/views/_settings.scss
It seems that when i made the change of styles for the select boxes override the custom select that it's in domains section that it's the only different from the rest of the application, so this is the fix.
- Add a background-color defined to override the default.
> [DR-1261] Fix issue in domains with custom select box style

- src/wwwroot/controllers/BillingCtrl.js
This is a fix for the meantime we decide what to do with that submenu.
- Add my plan link into submenu, so the user can go back without using the dropdown on the right top.
> [DR-1267] Add My plan link into submenu with false state

- src/spec/billing_spec.js
- src/spec/confirmation_spec.js
- src/spec/forgot-password_spec.js
- src/spec/login_spec.js
- src/spec/settings_spec.js
- src/wwwroot/controllers/HeaderCtrl.js
- src/wwwroot/controllers/MainCtrl.js
- src/wwwroot/index.html
- src/wwwroot/locales/en-translation.js
- src/wwwroot/locales/es-translation.js
- src/wwwroot/partials/header.html
- src/wwwroot/services/auth.js
- src/wwwroot/styles/core/_base.scss
- src/wwwroot/styles/modules/_button.scss
- src/wwwroot/styles/views/_header.scss
Add new trial informational header letting the user know when it's in a trial account, about to end and in an ended account.
- Add free trial date to Rootscope so we can use it again in Reports Limits.
- Add behaviour to show the correct text
- Responsive ready.
- Service ready to show the header as soon as we give to the webapp a freeTrialEndDate without making any changes.
> [DR-1283] Add new informational header

- src/wwwroot/controllers/MainCtrl.js
Hi, team
I fixed a problem when calling the endpoint `/status/limits` when is called with null in the accountName
PR related: https://github.com/DopplerRelay/relay-webapp/pull/124/files
Example:
> [DR-1368] - Fix issue HTTP 500 in the Login

- src/wwwroot/controllers/MainCtrl.js
- src/wwwroot/services/auth.js
Hi @mvillaseco, @nreal and @alegarciamina,
As @nreal found yesterday, we were not cleaning free trial header after logout:
This code fixes that and also removes the header if the user upgrades the account. 
I have also applied a little code refactoring.
Could you kindly review?
> [DR-1371] Remove trial period banner on logout

- src/wwwroot/controllers/MainCtrl.js
- src/wwwroot/services/auth.js
Hi @mvillaseco, @nreal and @alegarciamina,
It fixes the issue with the popup: when our flag in the local storage did not exist, it was not working fine.
The idea is showing the popup only one time, but if the expiration date is moved and expires again, show the popup again.
> [DR-1373] Trial popup

- README.md
It is a minor change in WebApp readme file, based on @alegarciamina issue during environment setup.
Could you verify?
> Add reference to Java SDK in readme

- src/spec/billing_spec.js
- src/spec/page-objects/billing-page.js
- src/wwwroot/controllers/BillingCtrl.js
- src/wwwroot/controllers/PlanCtrl.js
- src/wwwroot/partials/settings/my-plan.html
- src/wwwroot/styles/views/_settings.scss
Hi @andresmoschini ,
I've created this PR to start reviewing the code while continue working.
Changes:
- Show  "change plan" for free or paid users, but not when there are scheduled agreements 
- Only show DragMe if it is a free trial 
- Do not allow to choose the same plan that user already has (same plan is defined by comparing includedDeliveries and currentIpsPlanCount values between plan and current agreement) 
- Do not allow to choose plans cheaper than current plan, show a Contact Us button.
- Show billing information pre-loaded if exists
- Set initial value for slider based on current plan (defaultPlanDeliveries).
> [DR-1393] Allow upgrades on webapp

- src/wwwroot/app.js
It sends navigation events to Google Analytics, only if `ga` object exists (so, it will only work in PROD).
Could you kindly review?
> [DR-1435] Send navigation events to Google Analytics

- src/wwwroot/services/auth.js
Fix error modal rejection title on login by passing text instead of object to `$rootScope.addError`
> [DR-1471] Fix pending activation error

- src/wwwroot/locales/en-translation.js
- src/wwwroot/locales/es-translation.js
Hi @mvillaseco, could you review this changes?
My idea is to apply today in prod, there should be no rendering problems, right?
And a language question. @Juampi1790 defined this message: 
_You have to configure your DKIM, SPF and **subdomain tracking** to verify your domain_
But in my opinion it should be: 
_You have to configure your DKIM, SPF and **tracking subdomain** to verify your domain_
What do you think?
> Hotfix warning text

- src/wwwroot/services/auth.js
Fix issue with regex when user have a templates profile. Now we will allow anything after /templates/ and /templates only(without the '/')
> [DR-1551] Fix wrong regex in templates profile

- src/wwwroot/services/auth.js
It seems that we have a problem with the gulp task that adds the revision numbers, it's currently adding it into any templates string inside auth.js(maybe in all services).
This is an ugly but working fix. I add also a TODO to research this, buy for now, we can go with this solution.
> [DR-1551] Fix issue with revision numbers replacing templates string

- src/spec/page-objects/reports-page.js
- src/spec/reports_spec.js
- src/wwwroot/controllers/ReportsCtrl.js
- src/wwwroot/partials/reports/reports.html
Users can't see their limit status if it's zero
-Update reports view to show the limit status box always
-Create tests
N/A
N/A
> [DR-1589] Show limit status box if the daily limit is zero

- src/wwwroot/locales/en-translation.js
HotFix to remove "Doppler Relay" word in the english version to match the spanish. And also fix the problem.
> [DR-1597] Remove Doppler relay word that it wasnt the same as spanish version

- src/wwwroot/styles/core/_settings.scss
- src/wwwroot/web.config
Prevent missing default mime types on IIS servers
Add default mime types for ttf and eot font extensions
N/A
RFC References: https://www.iana.org/assignments/media-types/media-types.xhtml
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
> [DR-1621] Add mime fonts to prevent missing default mime types in IIS

- src/wwwroot/web.config
Prevent missing default mime types on IIS servers
Remove default mime types to override it with new ones
Add default mime types for ttf and eot font extensions
N/A
RFC References: https://www.iana.org/assignments/media-types/media-types.xhtml
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
> [DR-1621] Remove default mime types in IIS

- src/wwwroot/web.config
Possible collitions if IIS server have setted some mime font types
Remove custom mime types before override to prevent collitions with IIS
Thanks @andresmoschini to alert me about this more earlier, I was wrong about the IIS behavior with overriding in mime types
> Remove custom mime font types to prevent collitions

- src/wwwroot/template-editor/adapterService.js
- src/wwwroot/template-editor/index.html
Hi @mvillaseco and @cristiangiagante, 
It adds a layer between DropZone and our backend and by the moment it has a double to avoid HTTP calls.
See related changes in MSEditor: https://github.com/MakingSense/MSEditor/pull/1259
> [DR-1628] Prototype image uploading

- src/wwwroot/template-editor/adapterService.js
Jslint fails on build time using interpolation literal in get method and url path parameter
Change interpolation literal to concatenation
N/A
The stack trace throws an ugly message to locate the error.
Jslint error stack trace:
```js
events.js:183
throw er; // Unhandled 'error' event
^
Error
at new JS_Parse_Error (D:\MakingSense\relay-webapp\src\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:196:18)
at js_error (D:\MakingSense\relay-webapp\src\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:204:11)
at parse_error (D:\MakingSense\relay-webapp\src\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:314:9)
at Object.next_token [as input] (D:\MakingSense\relay-webapp\src\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:562:9)
at next …
```
> [OT] Fix interpolation string issue with jslint at build time

- .travis.yml
- build-webapp.cmd
- src/build-n-publish.sh
- src/build-w-docker.sh
- src/gulpfile.js
- src/package.json
- src/protractor-travis-conf.js
- src/run-w-docker.sh
- src/wwwroot/template-editor/rev-manifest.json
Hi @mvillaseco and @cristiangiagante,
With this change, Travis CI will run the build, and in that way, we will detect if something goes wrong with the build process.
I have also added our docker scripts, to allow me (and you too) to run and build it without installing the dependencies. I added _build_n_publish_, I know that by the moment we are not publishing the WebApp to our CDN, but I think that we could do it soon (1 year? :P).
Finally, I applied some cleaning in Travis CI process.
Could you kindly review?
**UPDATE:** I have fixed some other issues:
* QA Deployment process was not working (for about a month!)
* Reference to template editor .js file was wrong
> Improve Travis CI and add Docker scripts

- src/package.json
Update bower version because this lib deprecated all previous versions.
> [DR-XXXX] Update bower version

- src/wwwroot/locales/es-translation.js
We need to remove a missing space in a term of use string
- Remove space in spanish translation dictionary
N/A
N/A
> [DR-1692] Remove space in terms of use string at spanish language

- src/spec/template_spec.js
- src/wwwroot/controllers/TemplateCtrl.js
- src/wwwroot/partials/templates/template.html
- src/wwwroot/services/templates.js
We need to use classic template editor in legacy templates for accounts with MSEditor feature enabled.
We need to be able to save MSEditor template content
Update Template controller and related partial view to handle Legacy templates
Update Template service to save MSEditor templates and handle legacy templates
Tests added
N/A
Now, when a MSEditor template type is open to edit is not being called anymore the GET /.../templates/{id}/body WEB API call.
> [DR-1703] Use classic template editor for legacy templates in featured MSEditor accounts

- src/spec/page-objects/new-plan.js
- src/spec/settings_spec.js
- src/wwwroot/controllers/MainCtrl.js
- src/wwwroot/controllers/PlanCtrl.js
- src/wwwroot/locales/en-translation.js
- src/wwwroot/locales/es-translation.js
- src/wwwroot/partials/header.html
- src/wwwroot/partials/settings/my-plan.html
- src/wwwroot/services/auth.js
Hi team, 
The main behavior improvement of these changes is not allowing do upgrades or downgrades if the account has a cancellation date.
Additionally, it also makes our code more explicit about the semantic differences between trial end and canceled accounts.
Could you review? (I will not merge it during this sprint, I prefer adding some tests in the next one)
> [DR-1738] Cancellation blocks upgrades

- src/karma.conf.js
- src/spec/billing_spec.js
- src/wwwroot/controllers/TemplateCtrl.js
- src/wwwroot/controllers/TemplatesCtrl.js
- src/wwwroot/images/svg/preview.svg
- src/wwwroot/locales/en-translation.js
- src/wwwroot/locales/es-translation.js
- src/wwwroot/partials/templates/template.html
- src/wwwroot/partials/templates/templates.html
- src/wwwroot/styles/views/_templates.scss
Hi team!
Here I added 2 features:
- In the list of templates, I added one button to view in another window, the generated image.
- And when you create or edit a template, at the bottom you can see in real-time the rendered HTML, which is taken from the template content.
If someone wants to try it, you can go to this URL: [Relay QA](https://dopplerrelayqa.makingsense.com/)
And log in with username1@dopplerrelay.com and password1
If anyone has suggestions, please comment!
> [DM-52] Add preview templates

- src/wwwroot/template-editor/adapterService.js
The migration to version v1.0.1-build169 needs a file server setting in order to keep working the social follow component
> [DE-30] Html broken template editor. Added  file server setting

- src/spec/billing_spec.js
- src/spec/settings_spec.js
- src/wwwroot/controllers/PlanCtrl.js
- src/wwwroot/partials/settings/my-plan.html
- src/wwwroot/styles/views/_settings.scss
Hello team, this PR is aimed to make come changes on the plans available for customers of Relay, removing the `Premium`, `Pro` and `Basic` distinctions from the plans. For this purpose the second card was eliminated leaving only one central card (the looks of it are pending a review from the UX team)
How it would be now
How it was
> DD-144 Change plan selector slider
